name: Check PR for evmNetworkId Change

on:
  pull_request:
    types:
      - opened
      - synchronize  # Trigger on PR open and when changes are pushed to the PR

jobs:
  check_evm_network_id:
    runs-on: ubuntu-latest

    - name: Check out code and switch to development branch
      uses: actions/checkout@v2

    - name: Check if evmNetworkId has changed in PR
      run: |
        # Capture the current and previous versions of the evmNetworkId property
        file_content=$(cat src/configs/ubiquibot-config-default.ts)
        evm_network_id=$(echo "$file_content" | grep -o 'evmNetworkId: [0-9]*' | sed 's/evmNetworkId: //')
        echo $evm_network_id
        
    - name: Check out code and switch to development branch
      uses: actions/checkout@v2
      with:
        ref: development
      # This step checks out your code from the repository.

    - name: Read and Check evmNetworkId from development branch
      run: |
        # Read the content of the file from the development branch
        file_content=$(cat src/configs/ubiquibot-config-default.ts)

        # Use regular expression to extract the evmNetworkId value
        current_network_id=$(echo "$file_content" | grep -o 'evmNetworkId: [0-9]*' | sed 's/evmNetworkId: //')
        echo $current_network_id
        # Check the evmNetworkId value
        if [ "$current_network_id" == "$evm_network_id" ]; then
          echo "evmNetworkId is set to 100 in the development branch. It's correct."
        else
          echo "evmNetworkId is not set to 100 in the development branch. It's incorrect."
          exit 1  # Exit with a non-zero status code to indicate failure.
        fi
